### ISSUE TITLE
what meaning of the pose data in scene.nvm?

### ISSUE THREAD

**Issue by zdw-qingdao** [Phog/DeepBlending#2]
Data in scene.nvm is like following:
images/0001.jpg 2942.11 0.906324 -0.0199029 0.41902 -0.0510219 6.64597 0.397202 2.23612 0 0

Could you please tell me the meaning of every parameter?
Thanks a lot!

**Comment by Phog** [comment]
From the dataset readme:
"We use the NVM file format, which can be read by VisualSFM (http://ccwu.me/vsfm/)."

The data format is documented there as well: http://ccwu.me/vsfm/doc.html#nvm
