### ISSUE TITLE
why the camera parameters are different in one scene?

### ISSUE THREAD

**Issue by zdw-qingdao** [Phog/DeepBlending#3]
1 PINHOLE 1300 840 962.021 961.986 650 420
103 PINHOLE 1268 830 1047.61 1050.75 634 415
28 PINHOLE 1271 832 1043.21 1043.4 635.5 416

the camera parameters are different, why? I 'm confused..

**Comment by Phog** [comment]
Many of the scenes were capture with auto-focus enabled, which means that the focal length changes between each photo. As a result, I ran SfM without enforcing constant intrinsic parameters between every camera in the scene, so slight variation is to be expected.
